export const FRONTPAGE_ROUTE = '/auth'
export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'

export const MAINPAGE_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const LISTPAGE_ROUTE = '/mylist'
export const TRENDING_ROUTE = '/anime/trending'
export const SEASON_ROUTE = '/anime/season'
export const UPCOMING_ROUTE = '/anime/upcoming'
export const POPULAR_ROUTE = '/anime/popular'